# Generated by Django 2.2.16 on 2022-04-17 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20220415_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.URLField(db_index=True, unique=True, verbose_name='Коментарий')),
                ('text', models.TextField(help_text='Введите текст комментария', verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='сomment',
            field=models.ForeignKey(blank=True, help_text='Коментарии к  посту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='posts.Comment', verbose_name='Коментарии'),
        ),
    ]
